/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account-info`; params?: Router.UnknownInputParams; } | { pathname: `/add-member`; params?: Router.UnknownInputParams; } | { pathname: `/add-room`; params?: Router.UnknownInputParams; } | { pathname: `/add-tenant`; params?: Router.UnknownInputParams; } | { pathname: `/bill`; params?: Router.UnknownInputParams; } | { pathname: `/change-password`; params?: Router.UnknownInputParams; } | { pathname: `/data-backup`; params?: Router.UnknownInputParams; } | { pathname: `/edit-room`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/lodge-info`; params?: Router.UnknownInputParams; } | { pathname: `/meter`; params?: Router.UnknownInputParams; } | { pathname: `/room-detail`; params?: Router.UnknownInputParams; } | { pathname: `/utility-price`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/debt` | `/debt`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rooms` | `/rooms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/account-info`; params?: Router.UnknownOutputParams; } | { pathname: `/add-member`; params?: Router.UnknownOutputParams; } | { pathname: `/add-room`; params?: Router.UnknownOutputParams; } | { pathname: `/add-tenant`; params?: Router.UnknownOutputParams; } | { pathname: `/bill`; params?: Router.UnknownOutputParams; } | { pathname: `/change-password`; params?: Router.UnknownOutputParams; } | { pathname: `/data-backup`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-room`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/lodge-info`; params?: Router.UnknownOutputParams; } | { pathname: `/meter`; params?: Router.UnknownOutputParams; } | { pathname: `/room-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/utility-price`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/debt` | `/debt`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rooms` | `/rooms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/account-info${`?${string}` | `#${string}` | ''}` | `/add-member${`?${string}` | `#${string}` | ''}` | `/add-room${`?${string}` | `#${string}` | ''}` | `/add-tenant${`?${string}` | `#${string}` | ''}` | `/bill${`?${string}` | `#${string}` | ''}` | `/change-password${`?${string}` | `#${string}` | ''}` | `/data-backup${`?${string}` | `#${string}` | ''}` | `/edit-room${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/lodge-info${`?${string}` | `#${string}` | ''}` | `/meter${`?${string}` | `#${string}` | ''}` | `/room-detail${`?${string}` | `#${string}` | ''}` | `/utility-price${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/debt${`?${string}` | `#${string}` | ''}` | `/debt${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rooms${`?${string}` | `#${string}` | ''}` | `/rooms${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/account-info`; params?: Router.UnknownInputParams; } | { pathname: `/add-member`; params?: Router.UnknownInputParams; } | { pathname: `/add-room`; params?: Router.UnknownInputParams; } | { pathname: `/add-tenant`; params?: Router.UnknownInputParams; } | { pathname: `/bill`; params?: Router.UnknownInputParams; } | { pathname: `/change-password`; params?: Router.UnknownInputParams; } | { pathname: `/data-backup`; params?: Router.UnknownInputParams; } | { pathname: `/edit-room`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/lodge-info`; params?: Router.UnknownInputParams; } | { pathname: `/meter`; params?: Router.UnknownInputParams; } | { pathname: `/room-detail`; params?: Router.UnknownInputParams; } | { pathname: `/utility-price`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/debt` | `/debt`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rooms` | `/rooms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
